# Generated by Django 6.0.2 on 2026-03-02 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motherplant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(help_text='Unique device ID, e.g. plant01', max_length=64, unique=True)),
                ('name', models.CharField(blank=True, help_text='Human-friendly name', max_length=128)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_moisture', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='motherplant.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('moisture', 'Soil moisture')], max_length=32)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(help_text='Timestamp from device')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='motherplant.plant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['plant', 'type', 'timestamp'], name='motherplant_plant_i_107bf0_idx')],
            },
        ),
    ]
