# Generated by Django 6.0.2 on 2026-03-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motherplant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='type',
            field=models.CharField(choices=[('moisture', 'Moisture')], max_length=32),
        ),
    ]
