# Generated by Django 6.0.2 on 2026-03-09 14:58

from django.db import migrations


def delete_temperature_telemetry(apps, schema_editor):
    """Delete all temperature telemetry records as they are no longer supported."""
    Telemetry = apps.get_model("motherplant", "Telemetry")
    deleted_count, _ = Telemetry.objects.filter(type="temperature").delete()
    if deleted_count > 0:
        print(f"Deleted {deleted_count} temperature telemetry records")


class Migration(migrations.Migration):

    dependencies = [
        ('motherplant', '0003_alter_telemetry_type'),
    ]

    operations = [
        migrations.RunPython(delete_temperature_telemetry, migrations.RunPython.noop),
    ]
