# Generated by Django 6.0.3 on 2026-03-14 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motherplant', '0004_delete_temperature_telemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(help_text='Command name (e.g., water, calibrate)', max_length=64)),
                ('cmd_id', models.CharField(help_text='Unique command ID (UUID or int)', max_length=128)),
                ('sent_at', models.DateTimeField(help_text='When command was sent')),
                ('ack_at', models.DateTimeField(blank=True, help_text='When ack was received', null=True)),
                ('ok', models.BooleanField(blank=True, help_text='Ack success status', null=True)),
                ('error', models.TextField(blank=True, help_text='Error message from ack if failed')),
                ('raw_payload', models.JSONField(blank=True, help_text='Raw command payload for debugging', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='motherplant.plant')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['plant', 'cmd_id'], name='motherplant_plant_i_541846_idx'), models.Index(fields=['plant', 'sent_at'], name='motherplant_plant_i_0df006_idx')],
            },
        ),
    ]
